language : node_js

node_js:
    - 12.16
cache:
    directories:
        - node_modules
    
    install:
    - npm install
    
    script:
    - node --version
    - npm run package
    
    after_success:
    - npm run coverage
